### ISSUE TITLE
Kurulum Sonrası Title hatası

### ISSUE THREAD

**Issue by Fatih124** [karabayyazilim/softAdmin#6]
Kurulumu yapıp panelde login olunca aşağıdaki hatayı veriyor. Nasıl çözebilirim?

ErrorException
Undefined variable: title (View: C:\xampp\htdocs\laravel\resources\views\backend\app.blade.php)
http://localhost/laravel/public/admin/home
Hide solutions
$title is undefined

**Comment by karabayyazilim** [comment]
Merhaba aşağıdaki kodu çalıştırdınmı ?

`php artisan migrate --seed`

**Comment by Fatih124** [comment]
> Merhaba aşağıdaki kodu çalıştırdınmı ?
> 
> `php artisan migrate --seed`

Evet talimatlarda ki tüm adımları yaptım hepsi hata vermeden çalıştı. Ama yine de aynı hatayı alıyorum.

**Comment by karabayyazilim** [comment]
Buradaki yorum satırını açtınızmı ?

```
App\Providers\AppServiceProvider.php

//$data['settingss'] = Settings::all();
    if (isset($data['settingss'])){
        foreach ($data['settingss'] as $key){
            $settingss[$key->setting_key]=$key->setting_value;
        }
        view()->share($settingss);
    }
```
